export const data = [
    {
        id: 1,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 2,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 3,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 4,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 5,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    }

,
    {
        id: 7,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 8,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 9,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 10,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 11,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 12,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 13,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 14,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 15,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    },
    {
        id: 16,
        projectName : "Simple table",
        clientName: "client name",
        projectValue: "project value",
        projectManager: "Riadus Salehin",
        startDate: "28-3-2023",
        expectedDeadline: "30-3-2023",
        completionDate: "28-3-2023",
        estimatedHours: "4h",
        totalLoggedHours: "4h",
        tasks: "Simple Table",
        milestones: "",
        payment: "unpaid",
        progress: "60%",
        deliverableStatus: 'panding',
        projectStatus: "in_progress",
    }

]
